---
- name: Playbook to add string in file
  hosts: linux
  tasks:
   - blockinfile:
      dest: /tmp/conditional
      insertafter: EOF
      state: present
      block: 
        "This is my CentOS VM"
     when: ansible_distribution_version == "7.5" and ansible_kernel == "4.18.0-240.1.1.el8_3.x86_64"
