---
- name: Playbook to demonstrate handlers
  hosts: hum0964-c-vm1
  tasks:
   - name: add hostname
     shell: hostname > /var/www/html/index.html

   - name: install apache
     yum:
       name: httpd
       state: present
     notify: restart_httpd

  handlers:
   - name: restart_httpd
     systemd:
       name: httpd
