---
- name: Playbook with one play multiple tasks
  hosts: hum0964-c-vm*
  tasks:
    - name: create user4000
      when: ansible_hostname == "hum0964-c-vm-1"
      user:
        name: user4000
        uid: 5000
        state: present
    - name: create group cloudadmins
      when: ansible_hostname == "hum0964-c-vm-1"
      group:
        name: cloudadmins
        gid: 2000
        state: present

    - name: install apache and nmap
      yum:
        name:
        -  httpd
        -  nmap
        state: latest
    - name: confirm service is running
      systemd:
        name: httpd
        state: started
        enabled: yes


