---
- name: Play for user and group creation
  hosts: hum0964-c-vm2
  vars_files:
   - vars/userinfo
  tasks:
    - name: create group10
      group:
       name: "{{ grouplist1 }}"
       state: present
    - name: create group20
      group:
       name: "{{ grouplist2 }}"
       state: present
    - name: create user10
      user:
       name: "{{ userlist1 }}"
       groups: "{{ grouplist1 }}"
       append: 1
       uid: 1800
    - name: create user20
      user:
       name: "{{ userlist2 }}"
       groups: "{{ grouplist2 }}"
       append: 1
       uid: 1900
       shell: /bin/bash
       home: /home/"{{ userlist2 }}"
