---
- name: Playbook to demonstrate handling of task failures
  hosts: linux
  tasks:
   - name: to make changes to /etc/profile file
     block:
      - name: add ssh session timeout value to file
        blockinfile:
          path: /etc/profile
          insertafter: EOF
          backup: yes
          state: present
          block: |
            export TMOUT=900

      - name: setting umask value to umask 0077
        lineinfile:
          path: /etc/profile
          regex: "^umask"
          line: "umask 0077"
          state: present

     rescue:
      - name: task to execute if any of above fails
        lineinfile:
          path: ~/.bash_profile
          regex: "^umask"
          line: "umask 0066"
          state: present

     always:
      - name: task to run irrespective of others
        debug: 
          msg: Execution completed
