---
- name: Playbook to demonstrate management of files and folders
  hosts: hum0964-c-vm1
  tasks:
    - name: task to create locfile
      file:
       path: /home/locfile
       state: touch
       mode: 0644
       owner: root
       group: root
    - name: task to copy locfile to /tmp directory
      copy:
       src: /home/locfile
       dest: /tmp
       owner: root
       group: root
       remote_src: true
       mode: 0444
    - name: task to set selinux type for file
      file:
       path: /tmp/locfile
       setype: etc_t
    - name: task to display status of file
      stat:
       path: /tmp/locfile
      register: stat_output
    - name: display status
      debug:
       var: stat_output

- name: Play to create files
  hosts: linux
  tasks:
    - name: create files on managed nodes
      file:
       path: /home/emptyfile
       state: touch
       mode: 0644
       owner: root
       group: root
