---
- name: Playbook to install software if defined
  hosts: hum0964-c-vm1
  vars:
    packages: nmap

  tasks:
   - name: Install "{{ packages }}" software
     yum:
       name: "{{ packages }}"
       state: latest
     when: packages is defined  
