---
- name: Playbook to create multiple users
  hosts: linux
  tasks:

    - name: Add user accounts
      user: 
        name: "{{ item.username }}"
        uid: "{{ item.userid }}"
        state: present

      loop: "{{ userinfo }}"
    
