---
- name: Removing required packages
  package:
    name: "{{ packages }}"
    state: absent
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" 


# tasks file for package_remove
