# ---
    - name: Create partition
      parted:
        device: "{{ item.device }}"
        number:  "{{ item.number }}"
        state: present
        part_start: "{{ item.part_start }}"
        part_end: "{{ item.part_end }}"
      loop: "{{ disk_details }}"

    - name: Create directory if does not exist
      file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
      loop: "{{ disk_details }}"

    - name: Create a xfs filesystem
      filesystem:
        fstype: "{{ item.fstype }}"
        dev: "{{ item.partition }}"
      loop: "{{ disk_details }}"

    - name: Mount sdc1 to dir
      mount:
        path: "{{ item.path }}"
        src: "{{ item.partition }}"
        fstype: "{{ item.fstype }}"
        state: mounted
      loop: "{{ disk_details }}"
